"""Fixtures for Person B's PROV suite.

RULES.md §6.1 — nothing in this directory may import QGIS. Run it with:

    make test-prov
"""

from __future__ import annotations

import json
import pathlib
import shutil

import pytest

from geoprovenance.storage.store import ProvenanceStore

FIXTURES = pathlib.Path(__file__).resolve().parents[1] / "fixtures"


@pytest.fixture()
def store(tmp_path):
    """A fresh, empty store. Closed automatically."""
    s = ProvenanceStore(tmp_path / "prov.db")
    yield s
    s.close()


@pytest.fixture()
def recorded_store(tmp_path):
    """The committed fixture record, on a copy so a test can write to it.

    This one matters more than a hand-built case: `mock_provenance.db` was
    generated by `tests/fixtures/build_fixtures.py` months before this module
    existed, so agreeing with it is real evidence rather than a restatement of
    the code under test.
    """
    copy = tmp_path / "mock_provenance.db"
    shutil.copyfile(FIXTURES / "mock_provenance.db", copy)
    s = ProvenanceStore(copy)
    yield s
    s.close()


@pytest.fixture(scope="module")
def ids() -> dict[str, str]:
    """readable name -> UUID, the same map B and C read (fixtures/README.md)."""
    return json.loads((FIXTURES / "mock_ids.json").read_text())
