"""Channel 1 and 2: the Processing post-execution hook, and a processing.run wrapper.

Owner: Person A.  Sub-phase: A3.

    ┌──────────────────────────────────────────────────────────────────────┐
    │  UNVERIFIED (RULES.md §11.4, §5.11)                                  │
    │                                                                      │
    │  None of the QGIS-facing code below has been run — QGIS is not       │
    │  installed on the machine it was written on. Two things in           │
    │  particular are informed guesses that MUST be checked on first run:  │
    │                                                                      │
    │    1. The names ProcessingConfig uses for the post-execution script  │
    │       setting.                                                       │
    │    2. What variables QGIS puts in the hook script's namespace.       │
    │       Research doc §5.2 shows alg / parameters / context / results.  │
    │                                                                      │
    │  Rather than assume, the generated hook script hands its ENTIRE      │
    │  namespace to handle_post_execution(), which logs the names it       │
    │  actually received. The first Buffer you run answers the question,   │
    │  and the answer goes in docs/capture_coverage.md.                    │
    └──────────────────────────────────────────────────────────────────────┘

    §5.11 — which invocation paths actually fire the hook is an EMPIRICAL
    question answered in Week 4, not assumed from documentation. The Toolbox
    dialog, batch mode and the Graphical Modeler may take different code paths.
    That table is the RQ1 evidence.

Rules implemented
    §5.2 [HARD]  The wrapper preserves the original signature and return value
                 exactly, and NEVER swallows exceptions raised by the algorithm
                 itself. Only exceptions from capture code are caught.
    §5.3 [HARD]  The user's previous POST_EXECUTION_SCRIPT is read, stored, and
                 restored on unload. Clobbering their setting is a defect.
    §5.1 [HARD]  Nothing in here may raise into QGIS.
"""

from __future__ import annotations

import datetime as dt
import functools
import pathlib
from typing import Callable

from ..log import CRITICAL, INFO, WARNING, log, log_exception
from ..storage.store import utc_now_iso
from .engine import ProvenanceCaptureEngine

HOOK_FILENAME = "post_execution_hook.py"
PRE_HOOK_FILENAME = "pre_execution_hook.py"

#: Written to disk and pointed at by ProcessingConfig. Deliberately almost
#: empty — every line here is un-versioned code running inside QGIS, so it does
#: nothing but hand its namespace to the real implementation below.
HOOK_TEMPLATE = '''\
# GENERATED by geoprovenance/capture/hooks.py — do not edit.
# Runs {when} every QGIS Processing algorithm execution.
import sys

_PLUGIN_PARENT = {plugin_parent!r}
if _PLUGIN_PARENT not in sys.path:
    sys.path.insert(0, _PLUGIN_PARENT)

try:
    from geoprovenance.capture.hooks import {handler}
    {handler}(globals())
except Exception:  # noqa: BLE001 — a hook must never break the user's run
    try:
        import traceback
        from qgis.core import Qgis, QgsMessageLog
        QgsMessageLog.logMessage(
            "GeoProvenance {when}-execution hook failed:\\n" + traceback.format_exc(),
            "GeoProvenance", Qgis.Critical)
    except Exception:
        pass
'''

#: Set once we have logged each hook's namespace, so it appears in the log once
#: per session rather than once per algorithm run.
_namespace_logged = False
_pre_namespace_logged = False

#: A5 — where the pre-execution hook leaves the start time for the post hook.
#:
#: ONE slot, cleared on read, rather than a stack keyed by algorithm. If the
#: pre hook fires and the post hook does not — a crash, or an invocation path
#: that only runs one of them (§5.11 has not told us which yet) — a stack would
#: leak and hand a stale start time to the NEXT algorithm, silently inventing a
#: long duration. Overwriting a single slot degrades to "we lost one start
#: time", which is the failure this component is allowed to have (§5.1).
_pending_start: str | None = None

#: Beyond this, a pending start time is treated as orphaned rather than real.
#: A Processing algorithm that genuinely ran for an hour is possible; a start
#: time left behind by a run whose post hook never fired is likelier, and
#: reporting the latter as a duration would corrupt RQ2 (§8.4).
MAX_PENDING_START_AGE_S = 3600


# ---------------------------------------------------------------------------
# reading a QgsProcessingAlgorithm
# ---------------------------------------------------------------------------

#: QgsProcessingOutputDefinition types that denote a dataset rather than a
#: scalar result. outputNumber / outputString / outputHtml are NOT datasets.
_DATASET_OUTPUT_TYPES = frozenset({
    "outputVector", "outputRaster", "outputLayer", "outputFile", "outputFolder",
    "outputMultilayer", "outputPointCloud", "outputVectorTile",
})


def parameter_definitions(algorithm) -> dict[str, str]:
    """Map parameter/output name -> QGIS type string.

    This is the one thing the normalizer cannot work out on its own, and the
    reason the QGIS boundary sits exactly here: with this dict, everything
    downstream is pure Python (§3.3 — layer-valued parameters are lifted into
    inputs/outputs, scalars stay in `parameters`).
    """
    definitions: dict[str, str] = {}
    if algorithm is None:
        return definitions

    for accessor in ("parameterDefinitions", "outputDefinitions"):
        try:
            for definition in getattr(algorithm, accessor)():
                try:
                    definitions[definition.name()] = definition.type()
                except Exception:  # noqa: BLE001 — one odd definition is not fatal
                    continue
        except Exception:  # noqa: BLE001 — §5.1
            continue
    return definitions


def _algorithm_facts(algorithm) -> dict:
    """id / name / provider, each independently optional."""
    facts = {"algorithm_id": None, "algorithm_name": None, "provider": None}
    if algorithm is None:
        return facts
    try:
        facts["algorithm_id"] = algorithm.id()
    except Exception:  # noqa: BLE001
        pass
    try:
        facts["algorithm_name"] = algorithm.displayName()
    except Exception:  # noqa: BLE001
        pass
    try:
        provider = algorithm.provider()
        facts["provider"] = provider.id() if provider is not None else None
    except Exception:  # noqa: BLE001
        pass
    return facts


def resolve_algorithm(algorithm_or_id):
    """Accept either a QgsProcessingAlgorithm or its id string."""
    if algorithm_or_id is None or not isinstance(algorithm_or_id, str):
        return algorithm_or_id
    try:
        from qgis.core import QgsApplication
        return QgsApplication.processingRegistry().algorithmById(algorithm_or_id)
    except Exception:  # noqa: BLE001 — §5.1
        return None


# ---------------------------------------------------------------------------
# channel 1: the post-execution hook
# ---------------------------------------------------------------------------

def handle_pre_execution(scope: dict) -> None:
    """Called by the generated pre-execution script. Stamps the start time.

    A5. Without this the post-execution hook is the only thing that fires, and
    it fires *after* the run — so every job looked instantaneous and
    `post_hook` durations were not reportable in RQ2 at all (§8.4).

    Never raises (§5.1): a missing start time costs a duration, and the engine
    falls back to "now", which is the pre-A5 behaviour rather than a failure.
    """
    global _pending_start, _pre_namespace_logged
    try:
        if not _pre_namespace_logged:
            names = sorted(k for k in scope if not k.startswith("_"))
            log(f"pre-execution hook namespace: {names}. "
                f"Record this in docs/capture_coverage.md §4 (§5.11).", INFO)
            _pre_namespace_logged = True
        _pending_start = utc_now_iso()
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("pre-execution hook", exc)


def take_pending_start() -> str | None:
    """The start time the pre-execution hook left, consuming it. None if stale.

    Consumed on read so one start time can never be attributed to two runs.
    """
    global _pending_start
    pending, _pending_start = _pending_start, None
    if pending is None:
        return None
    try:
        age = (
            dt.datetime.now(dt.timezone.utc) - dt.datetime.fromisoformat(pending)
        ).total_seconds()
    except (TypeError, ValueError):
        return None
    if age < 0 or age > MAX_PENDING_START_AGE_S:
        log(f"discarding an orphaned start time ({age:.0f}s old) rather than "
            f"reporting it as a duration (§8.4)", WARNING)
        return None
    return pending


def handle_post_execution(scope: dict) -> None:
    """Called by the generated hook script with its whole namespace.

    Takes the namespace rather than named arguments precisely because what
    QGIS provides is the open empirical question (§5.11). Whatever is there
    gets used; whatever is missing degrades rather than raising.
    """
    global _namespace_logged

    try:
        if not _namespace_logged:
            names = sorted(k for k in scope if not k.startswith("_"))
            log(f"post-execution hook namespace: {names}. "
                f"Record this in docs/capture_coverage.md §4 (§5.11).", INFO)
            _namespace_logged = True

        engine = ProvenanceCaptureEngine.instance()
        if engine is None:
            return  # plugin not loaded; nothing to record, and that is fine

        algorithm = resolve_algorithm(scope.get("alg") or scope.get("algorithm"))
        facts = _algorithm_facts(algorithm)
        if not facts["algorithm_id"]:
            log("post-execution hook fired but the algorithm could not be "
                "identified — skipping (§5.11: record this case)", WARNING)
            return

        engine.record_algorithm_execution(
            algorithm_id=facts["algorithm_id"],
            algorithm_name=facts["algorithm_name"],
            provider=facts["provider"],
            parameters=scope.get("parameters"),
            parameter_definitions=parameter_definitions(algorithm),
            results=scope.get("results"),
            # A5 — the pre-execution hook left the start time in _pending_start.
            # If QGIS itself put one in the namespace, prefer that: it is the
            # more direct observation. Neither present means the engine defaults
            # to now and the run looks instantaneous, which is the pre-A5
            # limitation and stays recorded in docs/capture_coverage.md.
            started_at=scope.get("geoprovenance_started_at") or take_pending_start(),
            ended_at=scope.get("geoprovenance_ended_at") or utc_now_iso(),
            source="post_hook",
        )
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("post-execution hook", exc)


def _install_hook_script(hook_dir, *, when: str, filename: str, handler: str,
                         setting: str) -> Callable[[], None]:
    """Write one hook script and point a ProcessingConfig setting at it.

    Shared by the pre- and post-execution hooks, which differ only in those
    four values. Returns the undo (§5.3): it restores whatever the user had
    configured before, including an empty setting. Clobbering someone else's
    execution script is a defect, not a detail.
    """
    # Import first, write second. Writing the script before knowing whether
    # anything will ever run it left a generated file behind on a QGIS with no
    # Processing — a file nothing points at and unload has no undo for.
    try:
        from processing.core.ProcessingConfig import ProcessingConfig
    except ImportError as exc:
        log(f"Processing is not available, {when}-execution hook not installed: {exc}",
            WARNING)
        return lambda: None

    hook_dir = pathlib.Path(hook_dir)
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / filename

    plugin_parent = str(pathlib.Path(__file__).resolve().parents[2])
    hook_path.write_text(HOOK_TEMPLATE.format(
        plugin_parent=plugin_parent, handler=handler, when=when,
    ))

    # UNVERIFIED (§5.10) — the attribute name is an informed guess, so fall
    # back to the literal string rather than crashing on a rename.
    setting_name = getattr(ProcessingConfig, setting, setting)
    try:
        previous = ProcessingConfig.getSetting(setting_name)
    except Exception as exc:  # noqa: BLE001 — §5.1
        log_exception(f"could not read the existing {setting} setting", exc)
        return lambda: None

    try:
        ProcessingConfig.setSettingValue(setting_name, str(hook_path))
    except Exception as exc:  # noqa: BLE001
        log_exception(f"could not install the {when}-execution hook", exc)
        return lambda: None

    if previous:
        log(f"{when}-execution hook installed; your previous script ({previous}) "
            f"will be restored when the plugin unloads (§5.3)", WARNING)
    else:
        log(f"{when}-execution hook installed at {hook_path}", INFO)

    def restore() -> None:
        try:
            ProcessingConfig.setSettingValue(setting_name, previous or "")
            log(f"{when}-execution hook removed, previous setting restored", INFO)
        except Exception as exc:  # noqa: BLE001
            log_exception(f"could not restore {setting}", exc)

    return restore


def install_post_execution_hook(hook_dir) -> Callable[[], None]:
    """Point ProcessingConfig's post-execution setting at our script (§5.3)."""
    return _install_hook_script(
        hook_dir, when="post", filename=HOOK_FILENAME,
        handler="handle_post_execution", setting="POST_EXECUTION_SCRIPT",
    )


def install_pre_execution_hook(hook_dir) -> Callable[[], None]:
    """Point ProcessingConfig's pre-execution setting at our script (A5).

    This exists only to stamp a start time. Without it the post hook is the
    sole observer and it fires after the run, so every job looked
    instantaneous and `post_hook` durations were unreportable in RQ2 (§8.4).
    """
    return _install_hook_script(
        hook_dir, when="pre", filename=PRE_HOOK_FILENAME,
        handler="handle_pre_execution", setting="PRE_EXECUTION_SCRIPT",
    )


# ---------------------------------------------------------------------------
# channel 2: the processing.run wrapper
# ---------------------------------------------------------------------------

def install_run_wrapper(engine: ProvenanceCaptureEngine) -> Callable[[], None]:
    """Monkeypatch processing.run. Returns the un-patch (§5.4).

    The fallback channel for when the hook does not fire — and, until we know
    empirically where it does, a second observation of every scripted run. The
    duplicate is not waste: the two channels are de-duplicated on arrival
    (§5.9) and the difference between them is the RQ1 result (§8.3).
    """
    try:
        import processing
        from processing.tools import general
    except ImportError as exc:
        log(f"Processing is not available, run wrapper not installed: {exc}", WARNING)
        return lambda: None

    original = general.run
    if getattr(original, "_geoprovenance_wrapped", False):
        log("processing.run is already wrapped — not wrapping twice", WARNING)
        return lambda: None

    @functools.wraps(original)
    def wrapper(algOrName, parameters=None, *args, **kwargs):  # noqa: N803 — QGIS name
        started_at = utc_now_iso()
        try:
            results = original(algOrName, parameters, *args, **kwargs)
        except BaseException:
            # §5.2 [HARD] — record the failure, then re-raise UNTOUCHED. The
            # user's exception is theirs; we are only watching.
            _record(engine, algOrName, parameters, None, started_at, "failed")
            raise
        _record(engine, algOrName, parameters, results, started_at, "completed")
        return results

    wrapper._geoprovenance_wrapped = True  # noqa: SLF001 — our own marker

    general.run = wrapper
    processing.run = wrapper
    log("processing.run wrapper installed", INFO)

    def restore() -> None:
        general.run = original
        processing.run = original
        log("processing.run wrapper removed", INFO)

    return restore


def _record(engine, algorithm_or_id, parameters, results, started_at, status) -> None:
    """Observe one run from the wrapper. Never raises (§5.1)."""
    try:
        algorithm = resolve_algorithm(algorithm_or_id)
        facts = _algorithm_facts(algorithm)
        algorithm_id = facts["algorithm_id"] or (
            algorithm_or_id if isinstance(algorithm_or_id, str) else None
        )
        if not algorithm_id:
            return
        engine.record_algorithm_execution(
            algorithm_id=algorithm_id,
            algorithm_name=facts["algorithm_name"],
            provider=facts["provider"],
            parameters=parameters,
            parameter_definitions=parameter_definitions(algorithm),
            results=results,
            started_at=started_at,
            ended_at=utc_now_iso(),
            status=status,
            source="run_wrapper",
        )
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("processing.run wrapper", exc)


# ---------------------------------------------------------------------------

def install_all(engine: ProvenanceCaptureEngine, hook_dir) -> list[tuple[str, Callable]]:
    """Install the hook channels. Returns (description, undo) pairs for §5.4.

    All of them are installed because until §5.11's coverage table is filled in
    we do not know which invocation paths the hook covers, and a missed
    execution is an RQ1 result we would rather measure than suffer.

    The pre-execution hook is not a channel of its own — it records nothing.
    It only leaves a start time for the post hook to pick up (A5).
    """
    return [
        ("restore the pre-execution hook setting", install_pre_execution_hook(hook_dir)),
        ("restore the post-execution hook setting", install_post_execution_hook(hook_dir)),
        ("un-patch processing.run", install_run_wrapper(engine)),
    ]
