"""Channel 1 and 2: the Processing post-execution hook, and a processing.run wrapper.

Owner: Person A.  Sub-phase: A3.

    ┌──────────────────────────────────────────────────────────────────────┐
    │  UNVERIFIED (RULES.md §11.4, §5.11)                                  │
    │                                                                      │
    │  None of the QGIS-facing code below has been run — QGIS is not       │
    │  installed on the machine it was written on. Two things in           │
    │  particular are informed guesses that MUST be checked on first run:  │
    │                                                                      │
    │    1. The names ProcessingConfig uses for the post-execution script  │
    │       setting.                                                       │
    │    2. What variables QGIS puts in the hook script's namespace.       │
    │       Research doc §5.2 shows alg / parameters / context / results.  │
    │                                                                      │
    │  Rather than assume, the generated hook script hands its ENTIRE      │
    │  namespace to handle_post_execution(), which logs the names it       │
    │  actually received. The first Buffer you run answers the question,   │
    │  and the answer goes in docs/capture_coverage.md.                    │
    └──────────────────────────────────────────────────────────────────────┘

    §5.11 — which invocation paths actually fire the hook is an EMPIRICAL
    question answered in Week 4, not assumed from documentation. The Toolbox
    dialog, batch mode and the Graphical Modeler may take different code paths.
    That table is the RQ1 evidence.

Rules implemented
    §5.2 [HARD]  The wrapper preserves the original signature and return value
                 exactly, and NEVER swallows exceptions raised by the algorithm
                 itself. Only exceptions from capture code are caught.
    §5.3 [HARD]  The user's previous POST_EXECUTION_SCRIPT is read, stored, and
                 restored on unload. Clobbering their setting is a defect.
    §5.1 [HARD]  Nothing in here may raise into QGIS.
"""

from __future__ import annotations

import functools
import pathlib
from typing import Callable

from ..log import CRITICAL, INFO, WARNING, log, log_exception
from ..storage.store import utc_now_iso
from .engine import ProvenanceCaptureEngine

HOOK_FILENAME = "post_execution_hook.py"

#: Written to disk and pointed at by ProcessingConfig. Deliberately almost
#: empty — every line here is un-versioned code running inside QGIS, so it does
#: nothing but hand its namespace to the real implementation below.
HOOK_TEMPLATE = '''\
# GENERATED by geoprovenance/capture/hooks.py — do not edit.
# Runs after every QGIS Processing algorithm execution.
import sys

_PLUGIN_PARENT = {plugin_parent!r}
if _PLUGIN_PARENT not in sys.path:
    sys.path.insert(0, _PLUGIN_PARENT)

try:
    from geoprovenance.capture.hooks import handle_post_execution
    handle_post_execution(globals())
except Exception:  # noqa: BLE001 — a hook must never break the user's run
    try:
        import traceback
        from qgis.core import Qgis, QgsMessageLog
        QgsMessageLog.logMessage(
            "GeoProvenance post-execution hook failed:\\n" + traceback.format_exc(),
            "GeoProvenance", Qgis.Critical)
    except Exception:
        pass
'''

#: Set once we have logged the hook namespace, so it appears in the log once
#: per session rather than once per algorithm run.
_namespace_logged = False


# ---------------------------------------------------------------------------
# reading a QgsProcessingAlgorithm
# ---------------------------------------------------------------------------

#: QgsProcessingOutputDefinition types that denote a dataset rather than a
#: scalar result. outputNumber / outputString / outputHtml are NOT datasets.
_DATASET_OUTPUT_TYPES = frozenset({
    "outputVector", "outputRaster", "outputLayer", "outputFile", "outputFolder",
    "outputMultilayer", "outputPointCloud", "outputVectorTile",
})


def parameter_definitions(algorithm) -> dict[str, str]:
    """Map parameter/output name -> QGIS type string.

    This is the one thing the normalizer cannot work out on its own, and the
    reason the QGIS boundary sits exactly here: with this dict, everything
    downstream is pure Python (§3.3 — layer-valued parameters are lifted into
    inputs/outputs, scalars stay in `parameters`).
    """
    definitions: dict[str, str] = {}
    if algorithm is None:
        return definitions

    for accessor in ("parameterDefinitions", "outputDefinitions"):
        try:
            for definition in getattr(algorithm, accessor)():
                try:
                    definitions[definition.name()] = definition.type()
                except Exception:  # noqa: BLE001 — one odd definition is not fatal
                    continue
        except Exception:  # noqa: BLE001 — §5.1
            continue
    return definitions


def _algorithm_facts(algorithm) -> dict:
    """id / name / provider, each independently optional."""
    facts = {"algorithm_id": None, "algorithm_name": None, "provider": None}
    if algorithm is None:
        return facts
    try:
        facts["algorithm_id"] = algorithm.id()
    except Exception:  # noqa: BLE001
        pass
    try:
        facts["algorithm_name"] = algorithm.displayName()
    except Exception:  # noqa: BLE001
        pass
    try:
        provider = algorithm.provider()
        facts["provider"] = provider.id() if provider is not None else None
    except Exception:  # noqa: BLE001
        pass
    return facts


def resolve_algorithm(algorithm_or_id):
    """Accept either a QgsProcessingAlgorithm or its id string."""
    if algorithm_or_id is None or not isinstance(algorithm_or_id, str):
        return algorithm_or_id
    try:
        from qgis.core import QgsApplication
        return QgsApplication.processingRegistry().algorithmById(algorithm_or_id)
    except Exception:  # noqa: BLE001 — §5.1
        return None


# ---------------------------------------------------------------------------
# channel 1: the post-execution hook
# ---------------------------------------------------------------------------

def handle_post_execution(scope: dict) -> None:
    """Called by the generated hook script with its whole namespace.

    Takes the namespace rather than named arguments precisely because what
    QGIS provides is the open empirical question (§5.11). Whatever is there
    gets used; whatever is missing degrades rather than raising.
    """
    global _namespace_logged

    try:
        if not _namespace_logged:
            names = sorted(k for k in scope if not k.startswith("_"))
            log(f"post-execution hook namespace: {names}. "
                f"Record this in docs/capture_coverage.md §4 (§5.11).", INFO)
            _namespace_logged = True

        engine = ProvenanceCaptureEngine.instance()
        if engine is None:
            return  # plugin not loaded; nothing to record, and that is fine

        algorithm = resolve_algorithm(scope.get("alg") or scope.get("algorithm"))
        facts = _algorithm_facts(algorithm)
        if not facts["algorithm_id"]:
            log("post-execution hook fired but the algorithm could not be "
                "identified — skipping (§5.11: record this case)", WARNING)
            return

        engine.record_algorithm_execution(
            algorithm_id=facts["algorithm_id"],
            algorithm_name=facts["algorithm_name"],
            provider=facts["provider"],
            parameters=scope.get("parameters"),
            parameter_definitions=parameter_definitions(algorithm),
            results=scope.get("results"),
            # The pre-execution hook, when A5 adds it, leaves the start time in
            # the scope for us. Until then the engine defaults it to now, which
            # makes the run look instantaneous — an honest limitation, recorded
            # in docs/capture_coverage.md rather than papered over.
            started_at=scope.get("geoprovenance_started_at"),
            ended_at=scope.get("geoprovenance_ended_at") or utc_now_iso(),
            source="post_hook",
        )
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("post-execution hook", exc)


def install_post_execution_hook(hook_dir) -> Callable[[], None]:
    """Point ProcessingConfig at our hook script. Returns the undo (§5.3).

    The undo restores whatever the user had configured before, including an
    empty setting. Clobbering someone else's post-execution script is a defect,
    not a detail.
    """
    hook_dir = pathlib.Path(hook_dir)
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / HOOK_FILENAME

    plugin_parent = str(pathlib.Path(__file__).resolve().parents[2])
    hook_path.write_text(HOOK_TEMPLATE.format(plugin_parent=plugin_parent))

    try:
        from processing.core.ProcessingConfig import ProcessingConfig
    except ImportError as exc:
        log(f"Processing is not available, post-execution hook not installed: {exc}",
            WARNING)
        return lambda: None

    setting_name = getattr(ProcessingConfig, "POST_EXECUTION_SCRIPT", "POST_EXECUTION_SCRIPT")
    try:
        previous = ProcessingConfig.getSetting(setting_name)
    except Exception as exc:  # noqa: BLE001 — §5.1
        log_exception("could not read the existing POST_EXECUTION_SCRIPT setting", exc)
        return lambda: None

    try:
        ProcessingConfig.setSettingValue(setting_name, str(hook_path))
    except Exception as exc:  # noqa: BLE001
        log_exception("could not install the post-execution hook", exc)
        return lambda: None

    if previous:
        log(f"post-execution hook installed; your previous script ({previous}) "
            f"will be restored when the plugin unloads (§5.3)", WARNING)
    else:
        log(f"post-execution hook installed at {hook_path}", INFO)

    def restore() -> None:
        try:
            ProcessingConfig.setSettingValue(setting_name, previous or "")
            log("post-execution hook removed, previous setting restored", INFO)
        except Exception as exc:  # noqa: BLE001
            log_exception("could not restore POST_EXECUTION_SCRIPT", exc)

    return restore


# ---------------------------------------------------------------------------
# channel 2: the processing.run wrapper
# ---------------------------------------------------------------------------

def install_run_wrapper(engine: ProvenanceCaptureEngine) -> Callable[[], None]:
    """Monkeypatch processing.run. Returns the un-patch (§5.4).

    The fallback channel for when the hook does not fire — and, until we know
    empirically where it does, a second observation of every scripted run. The
    duplicate is not waste: the two channels are de-duplicated on arrival
    (§5.9) and the difference between them is the RQ1 result (§8.3).
    """
    try:
        import processing
        from processing.tools import general
    except ImportError as exc:
        log(f"Processing is not available, run wrapper not installed: {exc}", WARNING)
        return lambda: None

    original = general.run
    if getattr(original, "_geoprovenance_wrapped", False):
        log("processing.run is already wrapped — not wrapping twice", WARNING)
        return lambda: None

    @functools.wraps(original)
    def wrapper(algOrName, parameters=None, *args, **kwargs):  # noqa: N803 — QGIS name
        started_at = utc_now_iso()
        try:
            results = original(algOrName, parameters, *args, **kwargs)
        except BaseException:
            # §5.2 [HARD] — record the failure, then re-raise UNTOUCHED. The
            # user's exception is theirs; we are only watching.
            _record(engine, algOrName, parameters, None, started_at, "failed")
            raise
        _record(engine, algOrName, parameters, results, started_at, "completed")
        return results

    wrapper._geoprovenance_wrapped = True  # noqa: SLF001 — our own marker

    general.run = wrapper
    processing.run = wrapper
    log("processing.run wrapper installed", INFO)

    def restore() -> None:
        general.run = original
        processing.run = original
        log("processing.run wrapper removed", INFO)

    return restore


def _record(engine, algorithm_or_id, parameters, results, started_at, status) -> None:
    """Observe one run from the wrapper. Never raises (§5.1)."""
    try:
        algorithm = resolve_algorithm(algorithm_or_id)
        facts = _algorithm_facts(algorithm)
        algorithm_id = facts["algorithm_id"] or (
            algorithm_or_id if isinstance(algorithm_or_id, str) else None
        )
        if not algorithm_id:
            return
        engine.record_algorithm_execution(
            algorithm_id=algorithm_id,
            algorithm_name=facts["algorithm_name"],
            provider=facts["provider"],
            parameters=parameters,
            parameter_definitions=parameter_definitions(algorithm),
            results=results,
            started_at=started_at,
            ended_at=utc_now_iso(),
            status=status,
            source="run_wrapper",
        )
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("processing.run wrapper", exc)


# ---------------------------------------------------------------------------

def install_all(engine: ProvenanceCaptureEngine, hook_dir) -> list[tuple[str, Callable]]:
    """Install both channels. Returns (description, undo) pairs for §5.4.

    Both are installed because until §5.11's coverage table is filled in we do
    not know which invocation paths the hook covers, and a missed execution is
    an RQ1 result we would rather measure than suffer.
    """
    return [
        ("restore the post-execution hook setting", install_post_execution_hook(hook_dir)),
        ("un-patch processing.run", install_run_wrapper(engine)),
    ]
