"""Channel 1 and 2: the Processing post-execution hook, and a processing.run wrapper.

Owner: Person A.  Sub-phase: A3.

    ┌──────────────────────────────────────────────────────────────────────┐
    │  UNVERIFIED (RULES.md §11.4, §5.11)                                  │
    │                                                                      │
    │  None of the QGIS-facing code below has been run — QGIS is not       │
    │  installed on the machine it was written on. Two things in           │
    │  particular are informed guesses that MUST be checked on first run:  │
    │                                                                      │
    │    1. The names ProcessingConfig uses for the post-execution script  │
    │       setting.                                                       │
    │    2. What variables QGIS puts in the hook script's namespace.       │
    │       Research doc §5.2 shows alg / parameters / context / results.  │
    │                                                                      │
    │  Rather than assume, the generated hook script hands its ENTIRE      │
    │  namespace to handle_post_execution(), which logs the names it       │
    │  actually received. The first Buffer you run answers the question,   │
    │  and the answer goes in docs/capture_coverage.md.                    │
    └──────────────────────────────────────────────────────────────────────┘

    §5.11 — which invocation paths actually fire the hook is an EMPIRICAL
    question answered in Week 4, not assumed from documentation. The Toolbox
    dialog, batch mode and the Graphical Modeler may take different code paths.
    That table is the RQ1 evidence.

Rules implemented
    §5.2 [HARD]  The wrapper preserves the original signature and return value
                 exactly, and NEVER swallows exceptions raised by the algorithm
                 itself. Only exceptions from capture code are caught.
    §5.3 [HARD]  The user's previous POST_EXECUTION_SCRIPT is read, stored, and
                 restored on unload. Clobbering their setting is a defect.
    §5.1 [HARD]  Nothing in here may raise into QGIS.
"""

from __future__ import annotations

import datetime as dt
import functools
import pathlib
from typing import Callable

from ..log import CRITICAL, INFO, WARNING, log, log_exception
from ..storage.store import utc_now_iso
from .engine import ProvenanceCaptureEngine

HOOK_FILENAME = "post_execution_hook.py"
PRE_HOOK_FILENAME = "pre_execution_hook.py"

#: Written to disk and pointed at by ProcessingConfig. Deliberately almost
#: empty — every line here is un-versioned code running inside QGIS, so it does
#: nothing but hand its namespace to the real implementation below.
HOOK_TEMPLATE = '''\
# GENERATED by geoprovenance/capture/hooks.py — do not edit.
# Runs {when} every QGIS Processing algorithm execution.
import sys

_PLUGIN_PARENT = {plugin_parent!r}
if _PLUGIN_PARENT not in sys.path:
    sys.path.insert(0, _PLUGIN_PARENT)

try:
    from geoprovenance.capture.hooks import {handler}
    {handler}(globals())
except Exception:  # noqa: BLE001 — a hook must never break the user's run
    try:
        import traceback
        from qgis.core import Qgis, QgsMessageLog
        QgsMessageLog.logMessage(
            "GeoProvenance {when}-execution hook failed:\\n" + traceback.format_exc(),
            "GeoProvenance", Qgis.Critical)
    except Exception:
        pass
'''

#: Set once we have logged each hook's namespace, so it appears in the log once
#: per session rather than once per algorithm run.
_namespace_logged = False
_pre_namespace_logged = False

#: A5 — where the pre-execution hook leaves the start time for the post hook.
#:
#: ONE slot, cleared on read, rather than a stack keyed by algorithm. If the
#: pre hook fires and the post hook does not — a crash, or an invocation path
#: that only runs one of them (§5.11 has not told us which yet) — a stack would
#: leak and hand a stale start time to the NEXT algorithm, silently inventing a
#: long duration. Overwriting a single slot degrades to "we lost one start
#: time", which is the failure this component is allowed to have (§5.1).
_pending_start: str | None = None

#: Beyond this, a pending start time is treated as orphaned rather than real.
#: A Processing algorithm that genuinely ran for an hour is possible; a start
#: time left behind by a run whose post hook never fired is likelier, and
#: reporting the latter as a duration would corrupt RQ2 (§8.4).
MAX_PENDING_START_AGE_S = 3600


# ---------------------------------------------------------------------------
# reading a QgsProcessingAlgorithm
# ---------------------------------------------------------------------------

#: QgsProcessingOutputDefinition types that denote a dataset rather than a
#: scalar result. outputNumber / outputString / outputHtml are NOT datasets.
_DATASET_OUTPUT_TYPES = frozenset({
    "outputVector", "outputRaster", "outputLayer", "outputFile", "outputFolder",
    "outputMultilayer", "outputPointCloud", "outputVectorTile",
})


def parameter_definitions(algorithm) -> dict[str, str]:
    """Map parameter/output name -> QGIS type string.

    This is the one thing the normalizer cannot work out on its own, and the
    reason the QGIS boundary sits exactly here: with this dict, everything
    downstream is pure Python (§3.3 — layer-valued parameters are lifted into
    inputs/outputs, scalars stay in `parameters`).
    """
    definitions: dict[str, str] = {}
    if algorithm is None:
        return definitions

    for accessor in ("parameterDefinitions", "outputDefinitions"):
        try:
            for definition in getattr(algorithm, accessor)():
                try:
                    definitions[definition.name()] = definition.type()
                except Exception:  # noqa: BLE001 — one odd definition is not fatal
                    continue
        except Exception:  # noqa: BLE001 — §5.1
            continue
    return definitions


def _algorithm_facts(algorithm) -> dict:
    """id / name / provider, each independently optional."""
    facts = {"algorithm_id": None, "algorithm_name": None, "provider": None}
    if algorithm is None:
        return facts
    try:
        facts["algorithm_id"] = algorithm.id()
    except Exception:  # noqa: BLE001
        pass
    try:
        facts["algorithm_name"] = algorithm.displayName()
    except Exception:  # noqa: BLE001
        pass
    try:
        provider = algorithm.provider()
        facts["provider"] = provider.id() if provider is not None else None
    except Exception:  # noqa: BLE001
        pass
    return facts


def resolve_algorithm(algorithm_or_id):
    """Accept either a QgsProcessingAlgorithm or its id string."""
    if algorithm_or_id is None or not isinstance(algorithm_or_id, str):
        return algorithm_or_id
    try:
        from qgis.core import QgsApplication
        return QgsApplication.processingRegistry().algorithmById(algorithm_or_id)
    except Exception:  # noqa: BLE001 — §5.1
        return None


# ---------------------------------------------------------------------------
# channel 1: the post-execution hook
# ---------------------------------------------------------------------------

def handle_pre_execution(scope: dict) -> None:
    """Called by the generated pre-execution script. Stamps the start time.

    A5. Without this the post-execution hook is the only thing that fires, and
    it fires *after* the run — so every job looked instantaneous and
    `post_hook` durations were not reportable in RQ2 at all (§8.4).

    Never raises (§5.1): a missing start time costs a duration, and the engine
    falls back to "now", which is the pre-A5 behaviour rather than a failure.
    """
    global _pending_start, _pre_namespace_logged
    try:
        if not _pre_namespace_logged:
            names = sorted(k for k in scope if not k.startswith("_"))
            log(f"pre-execution hook namespace: {names}. "
                f"Record this in docs/capture_coverage.md §4 (§5.11).", INFO)
            _pre_namespace_logged = True
        _pending_start = utc_now_iso()
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("pre-execution hook", exc)


def take_pending_start() -> str | None:
    """The start time the pre-execution hook left, consuming it. None if stale.

    Consumed on read so one start time can never be attributed to two runs.
    """
    global _pending_start
    pending, _pending_start = _pending_start, None
    if pending is None:
        return None
    try:
        age = (
            dt.datetime.now(dt.timezone.utc) - dt.datetime.fromisoformat(pending)
        ).total_seconds()
    except (TypeError, ValueError):
        return None
    if age < 0 or age > MAX_PENDING_START_AGE_S:
        log(f"discarding an orphaned start time ({age:.0f}s old) rather than "
            f"reporting it as a duration (§8.4)", WARNING)
        return None
    return pending


def handle_post_execution(scope: dict) -> None:
    """Called by the generated hook script with its whole namespace.

    Takes the namespace rather than named arguments precisely because what
    QGIS provides is the open empirical question (§5.11). Whatever is there
    gets used; whatever is missing degrades rather than raising.
    """
    global _namespace_logged

    try:
        if not _namespace_logged:
            names = sorted(k for k in scope if not k.startswith("_"))
            log(f"post-execution hook namespace: {names}. "
                f"Record this in docs/capture_coverage.md §4 (§5.11).", INFO)
            _namespace_logged = True

        engine = ProvenanceCaptureEngine.instance()
        if engine is None:
            return  # plugin not loaded; nothing to record, and that is fine

        algorithm = resolve_algorithm(scope.get("alg") or scope.get("algorithm"))
        facts = _algorithm_facts(algorithm)
        if not facts["algorithm_id"]:
            log("post-execution hook fired but the algorithm could not be "
                "identified — skipping (§5.11: record this case)", WARNING)
            return

        engine.record_algorithm_execution(
            algorithm_id=facts["algorithm_id"],
            algorithm_name=facts["algorithm_name"],
            provider=facts["provider"],
            parameters=scope.get("parameters"),
            parameter_definitions=parameter_definitions(algorithm),
            results=scope.get("results"),
            # A5 — the pre-execution hook left the start time in _pending_start.
            # If QGIS itself put one in the namespace, prefer that: it is the
            # more direct observation. Neither present means the engine defaults
            # to now and the run looks instantaneous, which is the pre-A5
            # limitation and stays recorded in docs/capture_coverage.md.
            started_at=scope.get("geoprovenance_started_at") or take_pending_start(),
            ended_at=scope.get("geoprovenance_ended_at") or utc_now_iso(),
            source="post_hook",
        )
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception("post-execution hook", exc)


def _install_hook_script(hook_dir, *, when: str, filename: str, handler: str,
                         setting: str) -> Callable[[], None]:
    """Write one hook script and point a ProcessingConfig setting at it.

    Shared by the pre- and post-execution hooks, which differ only in those
    four values. Returns the undo (§5.3): it restores whatever the user had
    configured before, including an empty setting. Clobbering someone else's
    execution script is a defect, not a detail.
    """
    # Import first, write second. Writing the script before knowing whether
    # anything will ever run it left a generated file behind on a QGIS with no
    # Processing — a file nothing points at and unload has no undo for.
    try:
        from processing.core.ProcessingConfig import ProcessingConfig
    except ImportError as exc:
        log(f"Processing is not available, {when}-execution hook not installed: {exc}",
            WARNING)
        return lambda: None

    hook_dir = pathlib.Path(hook_dir)
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / filename

    plugin_parent = str(pathlib.Path(__file__).resolve().parents[2])
    hook_path.write_text(HOOK_TEMPLATE.format(
        plugin_parent=plugin_parent, handler=handler, when=when,
    ))

    # UNVERIFIED (§5.10) — the attribute name is an informed guess, so fall
    # back to the literal string rather than crashing on a rename.
    setting_name = getattr(ProcessingConfig, setting, setting)
    try:
        previous = ProcessingConfig.getSetting(setting_name)
    except Exception as exc:  # noqa: BLE001 — §5.1
        log_exception(f"could not read the existing {setting} setting", exc)
        return lambda: None

    try:
        ProcessingConfig.setSettingValue(setting_name, str(hook_path))
    except Exception as exc:  # noqa: BLE001
        log_exception(f"could not install the {when}-execution hook", exc)
        return lambda: None

    if previous:
        log(f"{when}-execution hook installed; your previous script ({previous}) "
            f"will be restored when the plugin unloads (§5.3)", WARNING)
    else:
        log(f"{when}-execution hook installed at {hook_path}", INFO)

    def restore() -> None:
        try:
            ProcessingConfig.setSettingValue(setting_name, previous or "")
            log(f"{when}-execution hook removed, previous setting restored", INFO)
        except Exception as exc:  # noqa: BLE001
            log_exception(f"could not restore {setting}", exc)

    return restore


def install_post_execution_hook(hook_dir) -> Callable[[], None]:
    """Point ProcessingConfig's post-execution setting at our script (§5.3)."""
    return _install_hook_script(
        hook_dir, when="post", filename=HOOK_FILENAME,
        handler="handle_post_execution", setting="POST_EXECUTION_SCRIPT",
    )


def install_pre_execution_hook(hook_dir) -> Callable[[], None]:
    """Point ProcessingConfig's pre-execution setting at our script (A5).

    This exists only to stamp a start time. Without it the post hook is the
    sole observer and it fires after the run, so every job looked
    instantaneous and `post_hook` durations were unreportable in RQ2 (§8.4).
    """
    return _install_hook_script(
        hook_dir, when="pre", filename=PRE_HOOK_FILENAME,
        handler="handle_pre_execution", setting="PRE_EXECUTION_SCRIPT",
    )


# ---------------------------------------------------------------------------
# channel 2: the processing.run wrapper
# ---------------------------------------------------------------------------

def install_run_wrapper(engine: ProvenanceCaptureEngine) -> Callable[[], None]:
    """Monkeypatch processing.run. Returns the un-patch (§5.4).

    The fallback channel for when the hook does not fire — and, until we know
    empirically where it does, a second observation of every scripted run. The
    duplicate is not waste: the two channels are de-duplicated on arrival
    (§5.9) and the difference between them is the RQ1 result (§8.3).
    """
    try:
        import processing
        from processing.tools import general
    except ImportError as exc:
        log(f"Processing is not available, run wrapper not installed: {exc}", WARNING)
        return lambda: None

    original = general.run
    if getattr(original, "_geoprovenance_wrapped", False):
        log("processing.run is already wrapped — not wrapping twice", WARNING)
        return lambda: None

    @functools.wraps(original)
    def wrapper(algOrName, parameters=None, *args, **kwargs):  # noqa: N803 — QGIS name
        started_at = utc_now_iso()
        try:
            results = original(algOrName, parameters, *args, **kwargs)
        except BaseException:
            # §5.2 [HARD] — record the failure, then re-raise UNTOUCHED. The
            # user's exception is theirs; we are only watching.
            _observe(engine, algOrName, parameters, None, started_at, "failed",
                     source="run_wrapper", context="processing.run wrapper")
            raise
        _observe(engine, algOrName, parameters, results, started_at, "completed",
                 source="run_wrapper", context="processing.run wrapper")
        return results

    wrapper._geoprovenance_wrapped = True  # noqa: SLF001 — our own marker

    general.run = wrapper
    processing.run = wrapper
    log("processing.run wrapper installed", INFO)

    def restore() -> None:
        general.run = original
        processing.run = original
        log("processing.run wrapper removed", INFO)

    return restore


def _observe(engine, algorithm_or_id, parameters, results, started_at, status,
             *, source: str, context: str, branch: str | None = None) -> None:
    """Record one observation from inside a running algorithm. NEVER raises.

    ``_record`` guards its own body, but §5.1 [HARD] is about what reaches the
    user, and everything on the way to it — resolving the algorithm, the
    first-firing log line, `_record` being monkeypatched in a test — is on the
    same call stack as somebody's analysis. One more guard here costs nothing
    and is the difference between losing a record and aborting a run.
    """
    try:
        if branch is not None:
            _note_toolbox_branch(branch)
        _record(engine, algorithm_or_id, parameters, results, started_at, status,
                source=source, context=context)
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        try:
            log_exception(context, exc)
        except Exception:  # noqa: BLE001 — logging must not be the thing that raises
            pass


def _record(engine, algorithm_or_id, parameters, results, started_at, status,
            *, source: str = "run_wrapper", context: str = "processing.run wrapper") -> None:
    """Observe one run from a wrapper channel. Never raises (§5.1).

    ``source`` is the §5.9 / §8.3 channel label that ends up in
    ``activities.capture_channel``; ``context`` only names the caller in the log
    when something is swallowed, so a failure says which channel produced it.
    """
    try:
        algorithm = resolve_algorithm(algorithm_or_id)
        facts = _algorithm_facts(algorithm)
        algorithm_id = facts["algorithm_id"] or (
            algorithm_or_id if isinstance(algorithm_or_id, str) else None
        )
        if not algorithm_id:
            return
        engine.record_algorithm_execution(
            algorithm_id=algorithm_id,
            algorithm_name=facts["algorithm_name"],
            provider=facts["provider"],
            parameters=parameters,
            parameter_definitions=parameter_definitions(algorithm),
            results=results,
            started_at=started_at,
            ended_at=utc_now_iso(),
            status=status,
            source=source,
        )
    except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
        log_exception(context, exc)


# ---------------------------------------------------------------------------
# channel 4: the Processing Toolbox dialog
# ---------------------------------------------------------------------------
#
# Measured 26 Aug 2026, and the reason this channel exists: a Buffer and a
# Convex hull run from the Toolbox were caught ONLY by `history_signal`. The
# Toolbox does not go through `processing.run()`, so `run_wrapper` never fired,
# and the post-execution hook does not exist on QGIS 4. The history channel has
# no QgsProcessingAlgorithm in hand, so it lifts no files (§3.3) and records no
# start time — the database held two jobs, zero entities and zero durations.
#
# That is the invocation path a person actually uses, so "we noticed it
# happened" is not a good enough record. This channel sits where the Toolbox
# really executes and hands the engine what the history channel cannot: the
# algorithm object (hence the parameter type map, hence inputs/outputs) and a
# start time taken BEFORE the run.
#
# QGIS 4.2.1's `AlgorithmWidget.runAlgorithm()` has TWO branches, chosen by the
# algorithm's FlagNoThreading:
#
#     line 427   QgsProcessingAlgRunnerTask(alg, parameters, context, feedback)
#     line 452   execute(alg, parameters, context, feedback)
#
# Both are patched, because which one runs is a property of the algorithm, not
# of the Toolbox. Both are patched IN THE `algorithm_widget` NAMESPACE rather
# than at their source: `AlgorithmExecutor.execute` is also called by
# `Processing.runAlgorithm`, which is what `processing.run` already goes
# through, and patching there would double-count every scripted run.

TOOLBOX_SOURCE = "toolbox"

#: Which branch actually fired, logged once per session. This is RQ1 evidence
#: (§5.11) — the answer belongs in docs/capture_coverage.md §4.
_toolbox_branches_seen: set = set()


def _note_toolbox_branch(branch: str) -> None:
    if branch in _toolbox_branches_seen:
        return
    _toolbox_branches_seen.add(branch)
    log(f"Toolbox capture: first execution seen via the {branch} branch "
        f"— record this in docs/capture_coverage.md §4", INFO)


def install_toolbox_wrapper(engine: ProvenanceCaptureEngine) -> Callable[[], None]:
    """Wrap both Toolbox execution branches. Returns the un-patch (§5.4).

    Degrades to a no-op when Processing's GUI is not importable — a headless
    QGIS has no Toolbox, and that is not an error.
    """
    try:
        from processing.gui import algorithm_widget
    except ImportError as exc:
        log(f"Processing's Toolbox is not available, "
            f"toolbox wrapper not installed: {exc}", WARNING)
        return lambda: None

    restores: list[Callable[[], None]] = []

    _wrap_toolbox_task(engine, algorithm_widget, restores)
    _wrap_toolbox_execute(engine, algorithm_widget, restores)

    if not restores:
        return lambda: None

    log(f"Toolbox wrapper installed ({len(restores)} of 2 branches)", INFO)

    def restore() -> None:
        # Reverse order, same discipline as the CleanupStack (§5.4).
        for undo in reversed(restores):
            try:
                undo()
            except Exception as exc:  # noqa: BLE001 — §5.4: one failure must
                log_exception("removing the Toolbox wrapper", exc)  # not strand the rest
        log("Toolbox wrapper removed", INFO)

    return restore


def _wrap_toolbox_task(engine, algorithm_widget, restores: list) -> None:
    """The threaded branch: QgsProcessingAlgRunnerTask.

    The task is constructed before the run and emits ``executed(ok, results)``
    after it, so the two ends of the bracket are a construction and a signal.
    That is what gives this channel a real duration where the history channel
    has none.
    """
    original = getattr(algorithm_widget, "QgsProcessingAlgRunnerTask", None)
    if original is None:
        log("QgsProcessingAlgRunnerTask not found in the Toolbox module — "
            "threaded Toolbox runs will not be captured by this channel", WARNING)
        return
    if getattr(original, "_geoprovenance_wrapped", False):
        log("the Toolbox task is already wrapped — not wrapping twice", WARNING)
        return

    def task_factory(algorithm, parameters=None, *args, **kwargs):
        # §5.2 [HARD] — build the real task first and return it untouched. The
        # dialog calls isCanceled() on it and connects its own slot; anything
        # we hand back that is not the genuine article breaks the user's run.
        task = original(algorithm, parameters, *args, **kwargs)
        try:
            started_at = utc_now_iso()

            def on_executed(ok, results=None):
                _observe(
                    engine, algorithm, parameters,
                    results if ok else None, started_at,
                    "completed" if ok else "failed",
                    source=TOOLBOX_SOURCE, context="Toolbox task wrapper",
                    branch="threaded task",
                )

            task.executed.connect(on_executed)
        except Exception as exc:  # noqa: BLE001 — §5.1 [HARD]
            log_exception("attaching to the Toolbox task", exc)
        return task

    task_factory._geoprovenance_wrapped = True  # noqa: SLF001 — our own marker
    algorithm_widget.QgsProcessingAlgRunnerTask = task_factory

    def restore() -> None:
        algorithm_widget.QgsProcessingAlgRunnerTask = original

    restores.append(restore)


def _wrap_toolbox_execute(engine, algorithm_widget, restores: list) -> None:
    """The synchronous branch: AlgorithmExecutor.execute, as imported here.

    Taken by algorithms flagged FlagNoThreading, and by in-place edits.
    """
    original = getattr(algorithm_widget, "execute", None)
    if not callable(original):
        log("execute() not found in the Toolbox module — synchronous Toolbox "
            "runs will not be captured by this channel", WARNING)
        return
    if getattr(original, "_geoprovenance_wrapped", False):
        log("the Toolbox executor is already wrapped — not wrapping twice", WARNING)
        return

    @functools.wraps(original)
    def wrapper(alg, parameters=None, *args, **kwargs):
        started_at = utc_now_iso()
        try:
            ok, results = original(alg, parameters, *args, **kwargs)
        except BaseException:
            # §5.2 [HARD] — record it, then re-raise UNTOUCHED.
            _observe(engine, alg, parameters, None, started_at, "failed",
                     source=TOOLBOX_SOURCE, context="Toolbox execute wrapper",
                     branch="synchronous execute")
            raise
        _observe(engine, alg, parameters, results if ok else None, started_at,
                 "completed" if ok else "failed",
                 source=TOOLBOX_SOURCE, context="Toolbox execute wrapper",
                 branch="synchronous execute")
        # §5.2 — the caller unpacks exactly this pair.
        return ok, results

    wrapper._geoprovenance_wrapped = True  # noqa: SLF001 — our own marker
    algorithm_widget.execute = wrapper

    def restore() -> None:
        algorithm_widget.execute = original

    restores.append(restore)


# ---------------------------------------------------------------------------

def install_all(engine: ProvenanceCaptureEngine, hook_dir) -> list[tuple[str, Callable]]:
    """Install the hook channels. Returns (description, undo) pairs for §5.4.

    All of them are installed because until §5.11's coverage table is filled in
    we do not know which invocation paths the hook covers, and a missed
    execution is an RQ1 result we would rather measure than suffer.

    The pre-execution hook is not a channel of its own — it records nothing.
    It only leaves a start time for the post hook to pick up (A5).
    """
    return [
        ("restore the pre-execution hook setting", install_pre_execution_hook(hook_dir)),
        ("restore the post-execution hook setting", install_post_execution_hook(hook_dir)),
        ("un-patch processing.run", install_run_wrapper(engine)),
        ("un-patch the Processing Toolbox", install_toolbox_wrapper(engine)),
    ]
